rabbit:
  exchange:
    name: exchange
  stock:
    queue:
      name: stock-queue-2023

    routing:
      key: stockExchangeKey2023

  email:
    queue:
      name: email-queue-2023
    routing:
      key: emailExchangeKey2023